/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CoverTransferErrors,
  CoverTransferErrorsInterface,
} from "../CoverTransferErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "dest",
        type: "address",
      },
    ],
    name: "TransferFailed",
    type: "error",
  },
];

export class CoverTransferErrors__factory {
  static readonly abi = _abi;
  static createInterface(): CoverTransferErrorsInterface {
    return new utils.Interface(_abi) as CoverTransferErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoverTransferErrors {
    return new Contract(address, _abi, signerOrProvider) as CoverTransferErrors;
  }
}
