/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  CoverPoolFactoryErrors,
  CoverPoolFactoryErrorsInterface,
} from "../CoverPoolFactoryErrors";

const _abi = [
  {
    inputs: [],
    name: "FeeTierNotSupported",
    type: "error",
  },
  {
    inputs: [],
    name: "IdenticalTokenAddresses",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolAlreadyExists",
    type: "error",
  },
];

export class CoverPoolFactoryErrors__factory {
  static readonly abi = _abi;
  static createInterface(): CoverPoolFactoryErrorsInterface {
    return new utils.Interface(_abi) as CoverPoolFactoryErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CoverPoolFactoryErrors {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CoverPoolFactoryErrors;
  }
}
