/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISafeCast, ISafeCastInterface } from "../ISafeCast";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "toUint128",
    outputs: [
      {
        internalType: "uint128",
        name: "z",
        type: "uint128",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
    ],
    name: "toUint160",
    outputs: [
      {
        internalType: "uint160",
        name: "z",
        type: "uint160",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ISafeCast__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeCastInterface {
    return new utils.Interface(_abi) as ISafeCastInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeCast {
    return new Contract(address, _abi, signerOrProvider) as ISafeCast;
  }
}
