/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISafeTransfers,
  ISafeTransfersInterface,
} from "../ISafeTransfers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferIn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferOut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISafeTransfers__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeTransfersInterface {
    return new utils.Interface(_abi) as ISafeTransfersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeTransfers {
    return new Contract(address, _abi, signerOrProvider) as ISafeTransfers;
  }
}
