/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITwapOracle, ITwapOracleInterface } from "../ITwapOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IConcentratedPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "calculateAverageTick",
    outputs: [
      {
        internalType: "int24",
        name: "averageTick",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITwapOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ITwapOracleInterface {
    return new utils.Interface(_abi) as ITwapOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITwapOracle {
    return new Contract(address, _abi, signerOrProvider) as ITwapOracle;
  }
}
