/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OrderBookFactoryBase,
  OrderBookFactoryBaseInterface,
} from "../OrderBookFactoryBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "feeTierPageSpacing",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class OrderBookFactoryBase__factory {
  static readonly abi = _abi;
  static createInterface(): OrderBookFactoryBaseInterface {
    return new utils.Interface(_abi) as OrderBookFactoryBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderBookFactoryBase {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OrderBookFactoryBase;
  }
}
