/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { OrderBookView, OrderBookViewInterface } from "../OrderBookView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "endOffset",
        type: "uint256",
      },
    ],
    name: "getOrderKey",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class OrderBookView__factory {
  static readonly abi = _abi;
  static createInterface(): OrderBookViewInterface {
    return new utils.Interface(_abi) as OrderBookViewInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderBookView {
    return new Contract(address, _abi, signerOrProvider) as OrderBookView;
  }
}
