/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OrderBookEvents,
  OrderBookEventsInterface,
} from "../OrderBookEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "newOffset",
        type: "uint256",
      },
    ],
    name: "Fill",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "endOffset",
        type: "uint256",
      },
    ],
    name: "LiquidityProvided",
    type: "event",
  },
];

export class OrderBookEvents__factory {
  static readonly abi = _abi;
  static createInterface(): OrderBookEventsInterface {
    return new utils.Interface(_abi) as OrderBookEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderBookEvents {
    return new Contract(address, _abi, signerOrProvider) as OrderBookEvents;
  }
}
