/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OrderBookFactoryEvents20,
  OrderBookFactoryEvents20Interface,
} from "../OrderBookFactoryEvents20";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "book",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "BookCreated",
    type: "event",
  },
];

export class OrderBookFactoryEvents20__factory {
  static readonly abi = _abi;
  static createInterface(): OrderBookFactoryEvents20Interface {
    return new utils.Interface(_abi) as OrderBookFactoryEvents20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderBookFactoryEvents20 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OrderBookFactoryEvents20;
  }
}
