/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OrderBookEvents1155,
  OrderBookEvents1155Interface,
} from "../OrderBookEvents1155";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "endOffset",
        type: "uint256",
      },
    ],
    name: "Cancel",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Claim",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "pagePrice",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "takerToken",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "makerToken",
        type: "address",
      },
    ],
    name: "PageCreated",
    type: "event",
  },
];

export class OrderBookEvents1155__factory {
  static readonly abi = _abi;
  static createInterface(): OrderBookEvents1155Interface {
    return new utils.Interface(_abi) as OrderBookEvents1155Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderBookEvents1155 {
    return new Contract(address, _abi, signerOrProvider) as OrderBookEvents1155;
  }
}
