/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OrderBookEvents1155To20,
  OrderBookEvents1155To20Interface,
} from "../OrderBookEvents1155To20";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "endOffset",
        type: "uint256",
      },
    ],
    name: "Cancel",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Claim",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "newOffset",
        type: "uint256",
      },
    ],
    name: "Fill",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "endOffset",
        type: "uint256",
      },
    ],
    name: "LiquidityProvided",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "pageKey",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "pagePrice",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "takerTokenHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "makerTokenHash",
        type: "bytes32",
      },
    ],
    name: "PageCreated",
    type: "event",
  },
];

export class OrderBookEvents1155To20__factory {
  static readonly abi = _abi;
  static createInterface(): OrderBookEvents1155To20Interface {
    return new utils.Interface(_abi) as OrderBookEvents1155To20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderBookEvents1155To20 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OrderBookEvents1155To20;
  }
}
