/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TwapOracleInterface extends ethers.utils.Interface {
  functions: {
    "blockTime()": FunctionFragment;
    "calculateAverageTick(IRangePool,uint16)": FunctionFragment;
    "isPoolObservationsEnough(address,uint16)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "blockTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateAverageTick",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolObservationsEnough",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "blockTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateAverageTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPoolObservationsEnough",
    data: BytesLike
  ): Result;

  events: {};
}

export class TwapOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TwapOracleInterface;

  functions: {
    blockTime(overrides?: CallOverrides): Promise<[number]>;

    calculateAverageTick(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number] & { averageTick: number }>;

    isPoolObservationsEnough(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  blockTime(overrides?: CallOverrides): Promise<number>;

  calculateAverageTick(
    pool: string,
    twapLength: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  isPoolObservationsEnough(
    pool: string,
    twapLength: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    blockTime(overrides?: CallOverrides): Promise<number>;

    calculateAverageTick(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    isPoolObservationsEnough(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    blockTime(overrides?: CallOverrides): Promise<BigNumber>;

    calculateAverageTick(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPoolObservationsEnough(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blockTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateAverageTick(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPoolObservationsEnough(
      pool: string,
      twapLength: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
